export const Types = {
    OPEN_CART : "OPEN_CART",
    CLOSE_CART : "CLOSE_CART",
    SET_PRODUCTS : "SET_PRODUCTS",
    SELETED_PRODUCT : "SELETED_PRODUCT",
    RMV_SELETED_PRODUCT : "RMV_SELETED_PRODUCT",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART : "REMOVE_FROM_CART",
    CHANGE_COUNT_CART : "CHANGE_COUNT_CART",
    REMOVE_ALL_CART : "REMOVE_ALL_CART"
}